///////////////////////////////////////////////////////////
//  Battery.cs
//  Implementation of the Class Battery
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:36 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Common
{
    public class Battery
    {

        private int capacity;
        private string id;
        private double maxPower;

        public Battery()
        {
            capacity = 0;
        }

        ~Battery()
        {

        }

        /// 
        /// <param name="id"></param>
        /// <param name="maxPower"></param>
        /// <param name="capacity"></param>
        public Battery(string id, double maxPower, int capacity)
        {
            Id = id;
            MaxPower = maxPower;
            Capacity = capacity;
        }

        public int Capacity
        {
            get
            {
                return capacity;
            }
            set
            {
                capacity = value;
            }
        }

        public string Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

        public double MaxPower
        {
            get
            {
                return maxPower;
            }
            set
            {
                maxPower = value;
            }
        }

    }
}//end Battery