///////////////////////////////////////////////////////////
//  Battery.cs
//  Implementation of the Class Battery
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:36 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Common
{
    public class Battery
    {
        public double Capacity { get; set; }

        public string Id
        {
            get;
            set;
        }

        public double MaxPower
        {
            get;
            set;
        }

        public Enums.BatteryRezim State { get; set; }
        public Battery()
        {
            Capacity = 0;
        }

        ~Battery()
        {

        }

        /// 
        /// <param name="id"></param>
        /// <param name="maxPower"></param>
        /// <param name="capacity"></param>

        public Battery(double capacity, string id, double maxPower, Enums.BatteryRezim state)
        {
            if (capacity >= 0)
                Capacity = capacity;
            else
                throw new ArgumentException("Kapacitet ne sme biti negativan broj!");
            Id = id;
            if (maxPower >= 0)
                MaxPower = maxPower;
            else
                throw new ArgumentException("Max power ne sme biti negativan broj!");
            State = state;
        }

    }
}//end Battery