///////////////////////////////////////////////////////////
//  Consumer.cs
//  Implementation of the Class Consumer
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:37 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Common
{
    public class Consumer
    {

        private double energyConsumption;
        private string id;
        private Enums.ConsumerRezim rezim;


        public Consumer()
        {

        }

        ~Consumer()
        {

        }

        /// 
        /// <param name="id"></param>
        /// <param name="energyConsumption"></param>
        public Consumer( double energyConsumption , string id, Enums.ConsumerRezim rezim)
        {
            this.EnergyConsumption = energyConsumption;
            this.Id = id;
            this.Rezim = rezim;

        }

        public double EnergyConsumption
        {
            get
            {
                return energyConsumption;
            }
            set
            {
                energyConsumption = value;
            }
        }

        public string Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

        public Enums.ConsumerRezim Rezim { get => rezim; set => rezim = value; }
    }
}//end Consumer