///////////////////////////////////////////////////////////
//  Consumer.cs
//  Implementation of the Class Consumer
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:37 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Common
{
    public class Consumer
    {

        private double energyConsumption;
        private string id;
        private Enums.ConsumerRezim rezim;


        public Consumer()
        {

        }

        ~Consumer()
        {

        }

        /// 
        /// <param name="id"></param>
        /// <param name="energyConsumption"></param>
        public Consumer( double energyConsumption , string id, Enums.ConsumerRezim rezim)
        {
            int temp;
            if (id != null && Int32.TryParse(id, out temp) == true)
                this.Id = id;
            else if (id == null)
                throw new ArgumentNullException("Id ne sme biti null!");
            else
                throw new ArgumentException("Id moze sadrzati samo brojeve!");

            if (energyConsumption >= 0)
                this.EnergyConsumption = energyConsumption;
            else
                throw new ArgumentOutOfRangeException("Potrosnja ne sme biti negativna!");

            this.Rezim = rezim;

        }

        public double EnergyConsumption
        {
            get
            {
                return energyConsumption;
            }
            set
            {
                energyConsumption = value;
            }
        }

        public string Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

        public Enums.ConsumerRezim Rezim { get => rezim; set => rezim = value; }
    }
}//end Consumer