///////////////////////////////////////////////////////////
//  Consumer.cs
//  Implementation of the Class Consumer
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:37 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Common
{
    public class Consumer
    {

        private double energyConsumption;
        private string id;


        public Consumer()
        {

        }

        ~Consumer()
        {

        }

        /// 
        /// <param name="id"></param>
        /// <param name="energyConsumption"></param>
        public Consumer(string id, double energyConsumption)
        {

        }

        public double EnergyConsumption
        {
            get
            {
                return energyConsumption;
            }
            set
            {
                energyConsumption = value;
            }
        }

        public string Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

    }
}//end Consumer