///////////////////////////////////////////////////////////
//  EVCharger.cs
//  Implementation of the Class EVCharger
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:38 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Common
{
    public class EVCharger:Battery
    {

        bool charge;
        bool connected;

        public EVCharger()
        {

        }

        public EVCharger(double capacity, string id, double maxPower, Enums.BatteryRezim state) :base(maxPower,id,capacity,state)
        {
            this.Charge = false;
            this.Connected = false;
            
        }

        ~EVCharger()
        {

        }

        public bool Charge { get => charge; set => charge = value; }
        public bool Connected { get => connected; set => connected = value; }
    }
}