///////////////////////////////////////////////////////////
//  EVCharger.cs
//  Implementation of the Class EVCharger
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:38 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Common
{
    public class EVCharger
    {

        


        public EVCharger()
        {

        }

        ~EVCharger()
        {

        }

       
        

    }
}