///////////////////////////////////////////////////////////
//  EVCharger.cs
//  Implementation of the Class EVCharger
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:38 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace Common
{
    [DataContract]
    public class EVCharger:Battery
    {

        bool charge;
        bool connected;

        public EVCharger()
        {

        }

        public EVCharger(double capacity, string id, double maxPower, Enums.BatteryRezim state,bool charge,bool connected) :base(capacity,id,maxPower,state)
        {
            this.Charge = charge;
            this.Connected = connected;
            
        }

        ~EVCharger()
        {

        }
        [DataMember]
        public virtual bool Charge { get => charge; set => charge = value; }
        [DataMember]
        public virtual bool Connected { get => connected; set => connected = value; }
    }
}