///////////////////////////////////////////////////////////
//  SHES.cs
//  Implementation of the Class SHES
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:39 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;

namespace Common
{
    public class SHES
    {
       
        public SHES()
        {
           

        }

        ~SHES()
        {

        }

 
    }
}//end SHES