///////////////////////////////////////////////////////////
//  SolarPanel.cs
//  Implementation of the Class SolarPanel
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:40 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Runtime.Serialization;

namespace Common
{
    [DataContract]
    public class SolarPanel
    {

        private string id;
        private double maxPower;


        public SolarPanel()
        {

        }

        public SolarPanel(string id, double maxPower)
        {
            if (id == null)
                throw new ArgumentNullException("Id ne moze biti null!");
            else if (maxPower < 0)
                throw new ArgumentOutOfRangeException("Snaga ne sme biti negativna!");
            else { 
                Id = id;
                MaxPower = maxPower;
            }
        }


        ~SolarPanel()
        {

        }
        [DataMember]
        public string Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        [DataMember]
        public double MaxPower
        {
            get
            {
                return maxPower;
            }
            set
            {
                maxPower = value;
            }
        }



    }
}//end SolarPanel