///////////////////////////////////////////////////////////
//  SolarPanel.cs
//  Implementation of the Class SolarPanel
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:40 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;

namespace Common
{
    public class SolarPanel
    {

        private string id;
        private double maxPower;


        public SolarPanel()
        {

        }
        public SolarPanel(string id, double maxPower)
        {

            Id = id;
            MaxPower = maxPower;

        }


        ~SolarPanel()
        {

        }

        public string Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

        public double MaxPower
        {
            get
            {
                return maxPower;
            }
            set
            {
                maxPower = value;
            }
        }



    }
}//end SolarPanel