///////////////////////////////////////////////////////////
//  Utility.cs
//  Implementation of the Class Utility
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:40 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
namespace Common
{
    public class Utility
    {
        public Utility()
        {

        }

        public Utility(double power, double price)
        {

            if (price < 0)
                throw new ArgumentOutOfRangeException("Cena ne sme biti negativna!");
            else
            {
                Power = power;
                Price = price;
            }
           
        }

        ~Utility()
        {

        }

        /// 
        /// <param name="price"></param>
        public Utility(double price)
        {
            if (price < 0)
                throw new ArgumentOutOfRangeException("Cena ne sme biti negativna!");
            else
                this.Price = price;
        }

        /// 
        /// <param name="amount"></param>
      

        public virtual double Power { get; set; }

        public virtual double Price { get; set; }

    }
}//end Utility