///////////////////////////////////////////////////////////
//  Utility.cs
//  Implementation of the Class Utility
//  Generated by Enterprise Architect
//  Created on:      13-May-2021 9:09:40 PM
//  Original author: Lenovo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
namespace Common
{
    public class Utility
    {

        private double power;
        private double price;


        public Utility()
        {

        }

        public Utility(int p, double price)
        {
            Power = p;
            Price = price;
        }

        ~Utility()
        {

        }

        /// 
        /// <param name="price"></param>
        public Utility(double price)
        {

        }

        /// 
        /// <param name="amount"></param>
      

        public double Power
        {
            get
            {
                return power;
            }
            set
            {
                power = value;
            }
        }

        public double Price
        {
            get
            {
                return price;
            }
            set
            {
                price = value;
            }
        }

    }
}//end Utility